### ISSUE TITLE
Can you tell me how you created this app?

### ISSUE THREAD

**Issue by GJ-sanjay** [wambugu71/resumeio2pdf_download#1]
Seriously interested ... really curious about how you went about and did this

**Comment by wambugu71** [comment]
get intouch with me  on my  socials [linkedin](https://www.linkedin.com/in/wambugu-kinyua-1b362b26b/) or  [Email](mailto:wambugukinyua@proton.me)

**Comment by TeekayJnr** [comment]
> get intouch with me on my socials [linkedin](https://www.linkedin.com/in/wambugu-kinyua-1b362b26b/) or [Email](mailto:wambugukinyua@proton.me)

Bro the link doesnt work anymore. It keeps saying "Please check if renderToken is correct". Can you help fix it please
